### ISSUE TITLE
Sbocheck shows newer (than in repo) SBo packages as 'needs updating'

### ISSUE THREAD

**Issue by archfan** [pink-mist/sbotools#42]
[sbocheck.txt](https://github.com/pink-mist/sbotools/files/254120/sbocheck.txt)

I believe this is not actually intended? 
Maybe newer packages should be ignored or simply marked as such.

**Comment by archfan** [comment]
Before I go, I wanted to thank you all for creating this wonderful tool. It is a joy to use.

**Comment by pink-mist** [comment]
I'm afraid this is unavoidable because version strings aren't always in a form that makes them sortable and I intentionally made it do this because a false positive that you can verify yourself that you don't care about is better than not seeing a result that would have been hidden if one tried to determine which was higher.

However, I'm curious how you can have SBo packages that have higher versions installed than is on the repository -- have you used the slackbuilds.org git master perhaps? If so, I'd suggest you switch sbotools to use that as the repository instead, then the versions won't be mismatched.

See ```sboconfig -r```.

Or have you built them by editing the slackbuild script to use a newer version? Then you might want to take a look at the local overrides setting, see ```sboconfig -o```.

(This advice assumes you're using the latest 2.0 release candidate, 2.0RC7, available on the website).

**Comment by pink-mist** [comment]
Do note that just because I closed this issue doesn't mean you can't still comment here and try to convince me I'm wrong. I can reopen it again if I get convinced.

**Comment by archfan** [comment]
>> However, I'm curious how you can have SBo packages that have higher versions installed than is >> on the repository -- have you used the slackbuilds.org git master perhaps?
I'm using the latest release 2.0RC7 on Slackware 14.2 with the git master repo.

Well I've tried your suggestion that is using local overrides instead. Now it shows the local override as outdated even when the actual version on the git master is older than what I have locally.

Maybe you'll find a way to fix it some day.
[sbocheck.txt](https://github.com/pink-mist/sbotools/files/269328/sbocheck.txt)
